/*
 * File:   Hdw_Uart.c
 * Author: francois
 *
 * Created on 31 octobre 2014, 18:17
 */

#include <stdio.h>
#include <stdlib.h>
#include <xc.h>
#include "Type.h"
#include "Bio-Net.h"
#include "DC22M_Main.h"

void interrupt isr(void)
{
    // manage Timer 0 each 250µs it is why it is in first place to be faster
    if (TMR0IF & TMR0IE)
    {
        // Timer 0 overflow every 1ms +2%
        TMR0IF = 0;

        // manage No Rx delay
        if (u8RxNoDelay!=0)
        {
            // we decrease u8RxNoDelay down to 0
            u8RxNoDelay--;
        }
        else
        {
            // u8RxNoDelay has reach 0 so 1 up to 1,25ms has elapsed whitout receiving any char
            // we reset all bionet flag but only one time
            if (bRazFlagAllowed)
            {
                BioNetRazFlag();
                bRazFlagAllowed=FALSE;
            }
        }
        //**** end manage No Rx delay

        // manage 1ms
        u8Prescaler10ms++;

        if (u8Prescaler10ms==VARCYCLE)
        {
            u8Prescaler10ms=0;

            DC24It10ms();

            if (OERR) //RX Overrun
            {
                // Reset overrun
                CREN=0;
                CREN=1;
            }
        }

    }
    // is this a RX interrupt
    else if (RCIF & RCIE)
    {
        RCIF=0;
        BioNetRxInt();
    }
    // is this a TX interrupt
    else if (TXIF & TXIE)
    {
        // needs to be put at the end because the flag is always activated
        // but generates interrupt only if TXIE is activated
        // but if put above, the interrupt generated by the following statement
        // will be never served and TX will be served instead
        //TXIF=0;
        BioNetTxInt();
    }

}
